//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirthdayReminder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BirthdayReminder.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a new friend or editing the existing friend details is not allowed in the trial version of the application. Please buy the full version to use this feature and unlock lots of other features..
        /// </summary>
        public static string AddEditFriendNotAllowed {
            get {
                return ResourceManager.GetString("AddEditFriendNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday Reminder.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cards.
        /// </summary>
        public static string BdayCardsPgTitle {
            get {
                return ResourceManager.GetString("BdayCardsPgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday Message.
        /// </summary>
        public static string BdayMsgLabel {
            get {
                return ResourceManager.GetString("BdayMsgLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIRTHDAY REMINDER SETTINGS.
        /// </summary>
        public static string BdayReminderSettingsTitle {
            get {
                return ResourceManager.GetString("BdayReminderSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any contacts saved currently. Would you like to download your facebook Contacts ?.
        /// </summary>
        public static string BdaySetupMessage {
            get {
                return ResourceManager.GetString("BdaySetupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Birthdays.
        /// </summary>
        public static string BdaySetupTitle {
            get {
                return ResourceManager.GetString("BdaySetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string BirthdayLabel {
            get {
                return ResourceManager.GetString("BirthdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many Many Happy Returns Of The Day :). Happy Birthday !!.
        /// </summary>
        public static string BirthdayMessage {
            get {
                return ResourceManager.GetString("BirthdayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday On.
        /// </summary>
        public static string BirthdayOnLabel {
            get {
                return ResourceManager.GetString("BirthdayOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;s birthday Today. Tap to send him a message.
        /// </summary>
        public static string BirthdayReminderMessage {
            get {
                return ResourceManager.GetString("BirthdayReminderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wishes.
        /// </summary>
        public static string BirthdayWishTitle {
            get {
                return ResourceManager.GetString("BirthdayWishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial version of the application does not allow adding or editing friend details. Please buy the full version to use this feature and to unlock a lot of other features..
        /// </summary>
        public static string BuyAppForAddFriend {
            get {
                return ResourceManager.GetString("BuyAppForAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial version of the application does not allow more than 100 friends to be saved. Only 100 facebook friends have been saved. Please buy the full version for saving all facebook freinds and to unlock a lot of other features. After you purchase the full version, please synchronize the friend list by going to the Settings in order to download all friends..
        /// </summary>
        public static string BuyAppForAllFriends {
            get {
                return ResourceManager.GetString("BuyAppForAllFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial version of the application only allows up to 5 cards. Please buy the full version to save more cards and to unlock a lot of other features..
        /// </summary>
        public static string BuyAppForCard {
            get {
                return ResourceManager.GetString("BuyAppForCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial version of the application does not allow deletion of items. Please buy the full version to delete items and to unlock a lot of other features..
        /// </summary>
        public static string BuyAppForDelete {
            get {
                return ResourceManager.GetString("BuyAppForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial version of the application does not allow this feature. Please buy the full version to use this feature and to unlock a lot of other features..
        /// </summary>
        public static string BuyAppGenericMessage {
            get {
                return ResourceManager.GetString("BuyAppGenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial version of the application does not allow changing of settings. Please buy the full version to use this feature and to unlock a lot of other features..
        /// </summary>
        public static string BuyAppSaveSettings {
            get {
                return ResourceManager.GetString("BuyAppSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Full Version.
        /// </summary>
        public static string BuyFullVersion {
            get {
                return ResourceManager.GetString("BuyFullVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string BuyLabel {
            get {
                return ResourceManager.GetString("BuyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string CallLabel {
            get {
                return ResourceManager.GetString("CallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Has Exceeded.
        /// </summary>
        public static string CardLimitExceedCaption {
            get {
                return ResourceManager.GetString("CardLimitExceedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 10 cards cannot be added. Please delete some old cards if you want to add new cards..
        /// </summary>
        public static string CardLimitMsg {
            get {
                return ResourceManager.GetString("CardLimitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Card.
        /// </summary>
        public static string ChooseCardLabel {
            get {
                return ResourceManager.GetString("ChooseCardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Is Busy.
        /// </summary>
        public static string ConnOpenWarnCaption {
            get {
                return ResourceManager.GetString("ConnOpenWarnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        public static string ContactNoLabel {
            get {
                return ResourceManager.GetString("ContactNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contacts have not been synchronised in a while. Do you want to update them now ?.
        /// </summary>
        public static string ContactNotUpdatedMessage {
            get {
                return ResourceManager.GetString("ContactNotUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        public static string ContactsTitle {
            get {
                return ResourceManager.GetString("ContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contacts would now be synchronised and you will be redirected to the Contact Sync Screen. Do you wish to sync your contacts now ?.
        /// </summary>
        public static string ContactSyncRedirectMsg {
            get {
                return ResourceManager.GetString("ContactSyncRedirectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday Reminders Are Getting Created.
        /// </summary>
        public static string CreateBdayReminder {
            get {
                return ResourceManager.GetString("CreateBdayReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected items ?.
        /// </summary>
        public static string DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting cards is not allowed in the trial version of the application. Please buy the full version to use this feature and to unlock a lot of other features..
        /// </summary>
        public static string DeletingCardsNotAllowed {
            get {
                return ResourceManager.GetString("DeletingCardsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Profile Images.
        /// </summary>
        public static string DownloadImagesTitle {
            get {
                return ResourceManager.GetString("DownloadImagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Contacts Are Getting Downloaded.
        /// </summary>
        public static string DownloadingFbContact {
            get {
                return ResourceManager.GetString("DownloadingFbContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download profile images of your friends ? After downloading images, you will be able to see their phtotos in the start tile. But please be patient as this process may take a few minutes depending on your internet connection speed. Do you wish to download the images now ?.
        /// </summary>
        public static string DownloadnProfileImgMsg {
            get {
                return ResourceManager.GetString("DownloadnProfileImgMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Adding Card.
        /// </summary>
        public static string ErrAddCard {
            get {
                return ResourceManager.GetString("ErrAddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Adding Friend.
        /// </summary>
        public static string ErrAddFriend {
            get {
                return ResourceManager.GetString("ErrAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Displaying App Bar.
        /// </summary>
        public static string ErrAppBarDisplay {
            get {
                return ResourceManager.GetString("ErrAppBarDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading App Bar.
        /// </summary>
        public static string ErrAppBarLoad {
            get {
                return ResourceManager.GetString("ErrAppBarLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during initialisation check. Some of the functionalities may not work..
        /// </summary>
        public static string ErrAppInitialise {
            get {
                return ResourceManager.GetString("ErrAppInitialise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting data to be displayed.
        /// </summary>
        public static string ErrBindingData {
            get {
                return ResourceManager.GetString("ErrBindingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Building Birthday List.
        /// </summary>
        public static string ErrBuildBdayList {
            get {
                return ResourceManager.GetString("ErrBuildBdayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error During Deletion.
        /// </summary>
        public static string ErrDeleting {
            get {
                return ResourceManager.GetString("ErrDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Displaying Save Button.
        /// </summary>
        public static string ErrDisplaSaveBtn {
            get {
                return ResourceManager.GetString("ErrDisplaSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Logging In to Facebook.
        /// </summary>
        public static string ErrFbLogin {
            get {
                return ResourceManager.GetString("ErrFbLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Logging Out From Facebook.
        /// </summary>
        public static string ErrFbLogout {
            get {
                return ResourceManager.GetString("ErrFbLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisation Error.
        /// </summary>
        public static string ErrInitialiseTitle {
            get {
                return ResourceManager.GetString("ErrInitialiseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Sync Screen.
        /// </summary>
        public static string ErrLoadSyncScreen {
            get {
                return ResourceManager.GetString("ErrLoadSyncScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Navigating To Settings.
        /// </summary>
        public static string ErrNavigatingSettings {
            get {
                return ResourceManager.GetString("ErrNavigatingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error On Navigation.
        /// </summary>
        public static string ErrOnNavigation {
            get {
                return ResourceManager.GetString("ErrOnNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Opening Application.
        /// </summary>
        public static string ErrOpeningApp {
            get {
                return ResourceManager.GetString("ErrOpeningApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Posting On Facebook Wall.
        /// </summary>
        public static string ErrPostingToWall {
            get {
                return ResourceManager.GetString("ErrPostingToWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while renewing background agent.
        /// </summary>
        public static string ErrRenewBgndTask {
            get {
                return ResourceManager.GetString("ErrRenewBgndTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Birthdays.
        /// </summary>
        public static string ErrSaveBday {
            get {
                return ResourceManager.GetString("ErrSaveBday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Birthdays and Contacts.
        /// </summary>
        public static string ErrSaveBdayNContact {
            get {
                return ResourceManager.GetString("ErrSaveBdayNContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Settings.
        /// </summary>
        public static string ErrSaveSettings {
            get {
                return ResourceManager.GetString("ErrSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Friend Details.
        /// </summary>
        public static string ErrSavingFrndDtls {
            get {
                return ResourceManager.GetString("ErrSavingFrndDtls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error During Selection.
        /// </summary>
        public static string ErrSelecting {
            get {
                return ResourceManager.GetString("ErrSelecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Sending Email.
        /// </summary>
        public static string ErrSendingEmail {
            get {
                return ResourceManager.GetString("ErrSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Sending Message.
        /// </summary>
        public static string ErrSendingMessage {
            get {
                return ResourceManager.GetString("ErrSendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to facebook failed.
        /// </summary>
        public static string FbLoginFailedText {
            get {
                return ResourceManager.GetString("FbLoginFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string FbLoginFailedTitle {
            get {
                return ResourceManager.GetString("FbLoginFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Details.
        /// </summary>
        public static string FrndDtlsPgTitlle {
            get {
                return ResourceManager.GetString("FrndDtlsPgTitlle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Details.
        /// </summary>
        public static string FrndDtlsTitle {
            get {
                return ResourceManager.GetString("FrndDtlsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The details of the existing friend has been updated.
        /// </summary>
        public static string FrndDtlsUpdated {
            get {
                return ResourceManager.GetString("FrndDtlsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Details Updated.
        /// </summary>
        public static string FrndDtlsUpdatedTitle {
            get {
                return ResourceManager.GetString("FrndDtlsUpdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy Birthday.
        /// </summary>
        public static string HappyBdayMessage {
            get {
                return ResourceManager.GetString("HappyBdayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is getting saved or deleted. Please wait for a few seconds and try again..
        /// </summary>
        public static string ImageUploadDownloadBusyMsg {
            get {
                return ResourceManager.GetString("ImageUploadDownloadBusyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Synced.
        /// </summary>
        public static string LastSyncedLabel {
            get {
                return ResourceManager.GetString("LastSyncedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string LaterLabel {
            get {
                return ResourceManager.GetString("LaterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later this week.
        /// </summary>
        public static string LaterThisWkLabel {
            get {
                return ResourceManager.GetString("LaterThisWkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Page Is Getting Loaded.
        /// </summary>
        public static string LoadingFbPageMsg {
            get {
                return ResourceManager.GetString("LoadingFbPageMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Your Settings.
        /// </summary>
        public static string LoadingSettingsLabel {
            get {
                return ResourceManager.GetString("LoadingSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In To Facebook.
        /// </summary>
        public static string LoginFbBtnnLabel {
            get {
                return ResourceManager.GetString("LoginFbBtnnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out Of Facebook.
        /// </summary>
        public static string LogoutFbBtnLabel {
            get {
                return ResourceManager.GetString("LogoutFbBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string MainPageAllTitle {
            get {
                return ResourceManager.GetString("MainPageAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recent.
        /// </summary>
        public static string MainPageMostRcntTitle {
            get {
                return ResourceManager.GetString("MainPageMostRcntTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdays.
        /// </summary>
        public static string MainPageTtitle {
            get {
                return ResourceManager.GetString("MainPageTtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MessageLabel {
            get {
                return ResourceManager.GetString("MessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been posted.
        /// </summary>
        public static string MsgPostedFb {
            get {
                return ResourceManager.GetString("MsgPostedFb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Friend Has Been Added.
        /// </summary>
        public static string NewFrndAddedTitle {
            get {
                return ResourceManager.GetString("NewFrndAddedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new friend with the details has been successfully added.
        /// </summary>
        public static string NewFrndCreatedMsg {
            get {
                return ResourceManager.GetString("NewFrndCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allowed.
        /// </summary>
        public static string NotAllowedLabel {
            get {
                return ResourceManager.GetString("NotAllowedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Known.
        /// </summary>
        public static string NotKnownLabel {
            get {
                return ResourceManager.GetString("NotKnownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application only 100 cards right now to allow easier management. Please delete some old cards to save new ones..
        /// </summary>
        public static string Only100CardsMessage {
            get {
                return ResourceManager.GetString("Only100CardsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string PictureLabel {
            get {
                return ResourceManager.GetString("PictureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post To Wall.
        /// </summary>
        public static string PostToWall {
            get {
                return ResourceManager.GetString("PostToWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this App.
        /// </summary>
        public static string RateAppBtnLabel {
            get {
                return ResourceManager.GetString("RateAppBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like our app and it has made your life easier, please rate/buy it!.
        /// </summary>
        public static string RateAppText {
            get {
                return ResourceManager.GetString("RateAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind By Email.
        /// </summary>
        public static string RemindByEmailLabel {
            get {
                return ResourceManager.GetString("RemindByEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reminder.
        /// </summary>
        public static string ReminderTitle {
            get {
                return ResourceManager.GetString("ReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders Updated.
        /// </summary>
        public static string ReminderUpdatedTitle {
            get {
                return ResourceManager.GetString("ReminderUpdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated reminders for birthdays.
        /// </summary>
        public static string ReminderUpdateSuccess {
            get {
                return ResourceManager.GetString("ReminderUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Local Contact Details.
        /// </summary>
        public static string RetrieveLocalContact {
            get {
                return ResourceManager.GetString("RetrieveLocalContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Facebook Friend Details.
        /// </summary>
        public static string RetrievingFbFriend {
            get {
                return ResourceManager.GetString("RetrievingFbFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Birthdays.
        /// </summary>
        public static string SaveBdays {
            get {
                return ResourceManager.GetString("SaveBdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Friend Details.
        /// </summary>
        public static string SavingFrndDtls {
            get {
                return ResourceManager.GetString("SavingFrndDtls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Auto Email.
        /// </summary>
        public static string SendAutoEmailLabel {
            get {
                return ResourceManager.GetString("SendAutoEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are experiencing any issues or you have any suggestions/requests, please feel free to contact us !.
        /// </summary>
        public static string SendEmailText {
            get {
                return ResourceManager.GetString("SendEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Pictures.
        /// </summary>
        public static string SendPicLabel {
            get {
                return ResourceManager.GetString("SendPicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send us an email.
        /// </summary>
        public static string SendUsEmailBtnLabel {
            get {
                return ResourceManager.GetString("SendUsEmailBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default.
        /// </summary>
        public static string SetAsDefaultLabel {
            get {
                return ResourceManager.GetString("SetAsDefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Saved.
        /// </summary>
        public static string SettingsSavedLabel {
            get {
                return ResourceManager.GetString("SettingsSavedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been updated successfully.
        /// </summary>
        public static string SettingsUpdateSuccessMsg {
            get {
                return ResourceManager.GetString("SettingsUpdateSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Notifications.
        /// </summary>
        public static string ShowNotifLabel {
            get {
                return ResourceManager.GetString("ShowNotifLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Email.
        /// </summary>
        public static string SupportEmailLabel {
            get {
                return ResourceManager.GetString("SupportEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Contacts.
        /// </summary>
        public static string SyncContactsLabel {
            get {
                return ResourceManager.GetString("SyncContactsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Facebook Contacts.
        /// </summary>
        public static string SyncFbContactLabel {
            get {
                return ResourceManager.GetString("SyncFbContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not allowed in the trial version of the application. Please buy the full version of the application to use this feature and to unlock lots of other features..
        /// </summary>
        public static string SyncFeatureNotAllowed {
            get {
                return ResourceManager.GetString("SyncFeatureNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Internal.
        /// </summary>
        public static string SyncIntervalLabel {
            get {
                return ResourceManager.GetString("SyncIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string SyncIntrvlOptionAfter {
            get {
                return ResourceManager.GetString("SyncIntrvlOptionAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string SyncIntrvlOptionBefore {
            get {
                return ResourceManager.GetString("SyncIntrvlOptionBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string SyncIntrvlOptionDaily {
            get {
                return ResourceManager.GetString("SyncIntrvlOptionDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string SyncIntrvlOptionHour {
            get {
                return ResourceManager.GetString("SyncIntrvlOptionHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string SyncIntrvlOptionManual {
            get {
                return ResourceManager.GetString("SyncIntrvlOptionManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string SyncIntrvlOptionMin {
            get {
                return ResourceManager.GetString("SyncIntrvlOptionMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string SyncIntrvlOptionMonthly {
            get {
                return ResourceManager.GetString("SyncIntrvlOptionMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Time.
        /// </summary>
        public static string SyncIntrvlOptionOnTime {
            get {
                return ResourceManager.GetString("SyncIntrvlOptionOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string SyncIntrvlOptionSec {
            get {
                return ResourceManager.GetString("SyncIntrvlOptionSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string SyncIntrvlOptionWeekly {
            get {
                return ResourceManager.GetString("SyncIntrvlOptionWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Local Contacts.
        /// </summary>
        public static string SyncLocalContactLabel {
            get {
                return ResourceManager.GetString("SyncLocalContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Now.
        /// </summary>
        public static string SyncNowBtnLabel {
            get {
                return ResourceManager.GetString("SyncNowBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string TodayLabel {
            get {
                return ResourceManager.GetString("TodayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string TomorrowLabel {
            get {
                return ResourceManager.GetString("TomorrowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update birthday reminders.
        /// </summary>
        public static string UpdateBdayRemindr {
            get {
                return ResourceManager.GetString("UpdateBdayRemindr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Required.
        /// </summary>
        public static string WarnDtlsReq {
            get {
                return ResourceManager.GetString("WarnDtlsReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to Internet. Please try again with a working Internet Connection..
        /// </summary>
        public static string WarnInternetMsg {
            get {
                return ResourceManager.GetString("WarnInternetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and birthday are compulsory.
        /// </summary>
        public static string WarnNameBdayCompulsory {
            get {
                return ResourceManager.GetString("WarnNameBdayCompulsory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        public static string WarnNwTitle {
            get {
                return ResourceManager.GetString("WarnNwTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background agent has been disabled for this app. Please re-enable to get alerts and notifications. Go to Settings - Applications - Background Tasks. Select the checkbox to enable background tasks..
        /// </summary>
        public static string WarnReEnableBgTask {
            get {
                return ResourceManager.GetString("WarnReEnableBgTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item and then try again.
        /// </summary>
        public static string WarnSelectItem {
            get {
                return ResourceManager.GetString("WarnSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Try Again.
        /// </summary>
        public static string WarnTryAgain {
            get {
                return ResourceManager.GetString("WarnTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid hour value between 0 and 23.
        /// </summary>
        public static string WarnValidHourValue {
            get {
                return ResourceManager.GetString("WarnValidHourValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid minute value between 0 and 59.
        /// </summary>
        public static string WarnValidMinValue {
            get {
                return ResourceManager.GetString("WarnValidMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid seconds value between 0 and 59.
        /// </summary>
        public static string WarnValidSecvalue {
            get {
                return ResourceManager.GetString("WarnValidSecvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When to remind.
        /// </summary>
        public static string WhenToRemindLabel {
            get {
                return ResourceManager.GetString("WhenToRemindLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish By Email.
        /// </summary>
        public static string WishByEmailLabel {
            get {
                return ResourceManager.GetString("WishByEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact number.
        /// </summary>
        public static string YourContactNoLabel {
            get {
                return ResourceManager.GetString("YourContactNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email.
        /// </summary>
        public static string YourEmailLabel {
            get {
                return ResourceManager.GetString("YourEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string YourNameLabel {
            get {
                return ResourceManager.GetString("YourNameLabel", resourceCulture);
            }
        }
    }
}
